# Generated by Django 4.0.4 on 2022-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='mark',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='puissance',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='facturecar',
            name='montant',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='prix',
            field=models.FloatField(default=0),
        ),
    ]
