# Generated by Django 4.0.4 on 2022-05-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_model_car_mark_car_puissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
