# Generated by Django 4.0.4 on 2022-05-13 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10}$')]),
        ),
    ]
