# Generated by Django 4.0.4 on 2022-05-04 18:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=120, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10}$')])),
                ('type_Activity', models.CharField(max_length=12)),
                ('prix', models.FloatField(default=0)),
                ('address', models.CharField(max_length=120, null=True)),
                ('image', models.ImageField(upload_to='media/Activity/')),
                ('disponibilité', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activity', to='activity.activity')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_Activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FactureActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_facteur', models.DateField(auto_now=True)),
                ('mode_payment', models.CharField(choices=[('cach', 'cach'), ('Activityd', 'Activityd')], default='Activityd', max_length=120)),
                ('montant', models.FloatField(default=0)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.reservationactivity')),
            ],
        ),
    ]
