# Generated by Django 4.0.4 on 2022-05-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='mark',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reservationactivity',
            old_name='Activity',
            new_name='activity',
        ),
        migrations.AlterField(
            model_name='factureactivity',
            name='mode_payment',
            field=models.CharField(choices=[('cach', 'cach'), ('card', 'card')], default='card', max_length=120),
        ),
    ]
