# Generated by Django 4.0.4 on 2022-05-02 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10}$')])),
                ('type_chambre', models.CharField(choices=[('1', '1'), ('2', '2'), ('Family', 'Family')], max_length=12)),
                ('prix', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='media/pics')),
                ('disponibilité', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('adress', models.CharField(max_length=120)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambre_reserve', to='hotel.chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_facteur', models.DateField(auto_now=True)),
                ('mode_payment', models.CharField(choices=[('cach', 'cach'), ('card', 'card')], max_length=120)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='chambre',
            name='nome_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
