# Generated by Django 4.0.4 on 2022-05-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_facture_reservation_imagechambre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='mode_payment',
            field=models.CharField(choices=[('cach', 'cach'), ('card', 'card')], default='card', max_length=120),
        ),
    ]
