# Generated by Django 4.0.4 on 2022-05-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_facture_mode_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageChambre',
        ),
    ]
